FROM cgr.dev/chainguard/wolfi-base
LABEL org.opencontainers.image.source="https://github.com/uptime-industries/compute-blade-agent"

# Copy binaries generated by goreleaser
COPY compute-blade-agent bladectl /bin/

ENTRYPOINT ["/bin/compute-blade-agent"]
